# Generated by Django 3.1.2 on 2020-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='Emaili')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzusi')),
                ('message', models.TextField(verbose_name='Habar matni')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
    ]
