# Generated by Django 3.1.2 on 2020-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nomi')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Like')),
                ('seen', models.PositiveIntegerField(default=0, verbose_name='Seen')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='Comment')),
                ('share', models.PositiveIntegerField(default=0, verbose_name='Share')),
                ('added', models.CharField(max_length=100, verbose_name="Qo'shdi")),
                ('category', models.CharField(max_length=150, verbose_name='Mavzusi')),
                ('text', models.TextField(verbose_name='Moqala matni')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sanasi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sanasi'),
        ),
    ]
